version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: schedule_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: university_schedule
    ports:
      - "3306:3306"
    volumes:
      # This connects your script to the database container
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # This saves your data so it persists after restarts
      - db_data:/var/lib/mysql

volumes:
  db_data: